image: zeroonetechnology/fxl:ci

unit-test:
  script:
    - lein midje
  only:
    - merge_requests

linters:
  script:
    - joker --lint --working-dir src
    - joker --lint --working-dir test
    - clj-kondo --lint src test
    - lein kibit
  only:
    - merge_requests

test-coverage:
  script:
    - lein cloverage --fail-threshold 90
  only:
    - merge_requests
